Hmr/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import trash.views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^trash/', include('trash.urls', namespace='trash')),
    url(r'^$', trash.views.index, name='index'),
    url(r'^additem/$', trash.views.AddItem.as_view(), name='additem'),
    url(r'^bin/$', trash.views.TrashBins.as_view(), name='trashbins'),
    url(r'^aboutus/$', trash.views.AboutUs.as_view(), name='aboutus'),
    url(r'^bin/(\w+)/$', trash.views.show_binitems, name='show_binitems'),
    url(r'^search/$', trash.views.search, name='search'),
    url(r'^map/$', trash.views.openmap, name='openmap'),
    url(r'^login/$', trash.views.LogIn.as_view(), name='login'),
    url(r'^logout/$', trash.views.logout, name='logout'),
    url(r'^register/$', trash.views.Register.as_view(), name='register'),
    url(r'^rate/$', trash.views.rate, name='rate')
]

trash/urls.py
from django.conf.urls import url
from . import views

app_name = 'trash'
urlpatterns = [

]

trash/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid


class TrashGeoLoc(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    location = models.CharField(max_length=2058)

    def __str__(self):
        return self.location


class TrashMaterial(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=512)
    description = models.CharField(max_length=2058)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TrashBin(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=512)
    description = models.CharField(max_length=128)
    color = models.CharField(max_length=64)
    created_date = models.DateTimeField(auto_now_add=True)
    # optional foreign key for open data trashbin locations
    trash_loc = models.ForeignKey(TrashGeoLoc, on_delete=models.CASCADE, blank=True, null=True)
    common_location = models.CharField(max_length=256, null=True, blank=True)
    state_of_items = models.CharField(max_length=256, null=True, blank=True)
    not_included = models.CharField(max_length=256, null=True, blank=True)
    avatar_name = models.CharField(max_length=128, null=True, blank=True)

    def __str__(self):
        return self.name


class TrashItem(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=512)
    description = models.CharField(max_length=2058)
    material = models.ForeignKey(TrashMaterial, null=True, blank=True, on_delete=models.CASCADE)
    # a bin field referred to trash bin table
    bin = models.ForeignKey(TrashBin, default=None, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    # scan code
    sc_code = models.CharField(max_length=2058, default=None)
    # optional image file for image recognition
    item_img = models.BinaryField(default=None, null=True, blank=True)
    total_rating = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class ItemRating(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    item = models.ForeignKey(TrashItem, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    rate = models.IntegerField(default=0)

trash/forms.py
from django import forms

trash/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages
from django.http import HttpResponseRedirect, JsonResponse
from django.views import View
from django.db.models import Q
from django.contrib import auth
from django.views.decorators.csrf import ensure_csrf_cookie
import os
import json
import requests
from .models import *

COMMON_ERROR_MESSAGE = "An error has occurred."
NOT_FOUND_TRASH_BIN = "The trash bin is not existing."
ADD_ITEM_SUCCESSFULLY_MESSAGE = "Item has been added successfully."
SUCCESS_CSS_TAGS = "alert alert-success"
ERROR_CSS_TAGS = "alert alert-danger"
INFO_CSS_TAGS = "alert alert-info"
ERROR_SCAN = "Item could not be scanned, please try again."
NOT_FOUND_BAR_CODE = "NOTFOUND"
PASSWORD_CONFIRMATION_NOT_MATCH_MESSAGE = "The password confirmation doesn't match."
USERNAME_EXISTED_MESSAGE = "This Email has been taken."
REGISTER_SUCCESSFULLY_MESSAGE = "Register successfully!"
LOGGED_OUT_MESSAGE = "Log out successfully!"
LOGGED_IN_MESSAGE = "Log in successfully!"
LOGGED_IN_NOT_SUCCESSFULLY_MESSAGE = "Email or password is incorrect."


def index(request):
    return render(request, "trash/index.html")


class AddItem(View):  # Add Item page
    def get(self, request):  # request to open the add item page
        bins = TrashBin.objects.all()  # get all the current trash bins

        if request.method == 'GET' and 'scnf' in request.GET:
            context = {
                "scanner": request.GET["scnf"],
                "bins": bins,
            }
        else:
            context = {
                "bins": bins,
            }

        return render(request, "trash/additem.html", context)

    def post(self, request):  # request to create an item
        new_item = TrashItem.objects.create(name=request.POST["name"].strip(),
                                            description=request.POST["description"].strip(),
                                            bin_id=request.POST["bin"], sc_code=request.POST["sc_code"])
        new_item.save()

        messages.add_message(request, messages.SUCCESS, ADD_ITEM_SUCCESSFULLY_MESSAGE, extra_tags=SUCCESS_CSS_TAGS)
        return HttpResponseRedirect(reverse("index"))


class TrashBins(View):  # Trash Bin page
    def get(self, request):
        return render(request, "trash/bins.html")

    def post(self, request):
        pass


def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
        ]


def show_binitems(request, bin_name):
    try:
        bin = TrashBin.objects.get(name=bin_name.lower())
    except TrashBin.DoesNotExist:
        messages.add_message(request, messages.ERROR, NOT_FOUND_TRASH_BIN, extra_tags=ERROR_CSS_TAGS)
        return HttpResponseRedirect(reverse("index"))
    else:
        items = TrashItem.objects.filter(bin=bin).order_by("-total_rating", "name")[:30]

        if request.user.is_authenticated():
            idlist = []
            for i in items:
                idlist.append(i.id)
            voted_items_by_user = ItemRating.objects.filter(Q(user=request.user) & Q(item__id__in=idlist) & Q(rate=1))

            for item in items:
                for vi in voted_items_by_user:
                    if vi.item.id == item.id:
                        item.voted = "yes"
                        break
                    else:
                        item.voted = "no"

        return render(request, "trash/binitems.html", {"bin": bin, "items": items})


def search(request):  # search item by title or bar code number
    if request.GET["criteria"] == NOT_FOUND_BAR_CODE:
        # message for not found bar code
        messages.add_message(request, messages.ERROR, ERROR_SCAN, ERROR_CSS_TAGS)
        return HttpResponseRedirect(reverse("index"))
    elif (request.GET["criteria"] != "") & (request.GET["criteria"] != NOT_FOUND_BAR_CODE):
        # searching item
        criteria = request.GET["criteria"].lower().strip()
        if criteria[:4] == "scnr":
            result = TrashItem.objects.filter(
                Q(name__contains=criteria[4:]) | Q(sc_code__contains=criteria[4:])).order_by(
                "-total_rating", "bin__name")
        else:
            result = TrashItem.objects.filter(Q(name__icontains=criteria) | Q(sc_code__contains=criteria)).order_by(
                "-total_rating", "bin__name")
        # if the scanned number was not found go directly to the add page and show a message there
        if (criteria[:4] == "scnr") & (not result.count()):
            criteria = criteria[4:]
            return HttpResponseRedirect("/additem/?scnf=" + criteria)

        elif (criteria[:4] == "scnr") & (result.count()):
            criteria = criteria[4:]

    else:
        # search all
        result = TrashItem.objects.order_by("-total_rating", "-created_date")[:30]

    if request.user.is_authenticated():
        idlist = []
        for i in result:
            idlist.append(i.id)
        voted_items_by_user = ItemRating.objects.filter(Q(user=request.user) & Q(item__id__in=idlist) & Q(rate=1))

        for item in result:
            for vi in voted_items_by_user:
                if vi.item.id == item.id:
                    item.voted = "yes"
                    break
                else:
                    item.voted = "no"

    context = {
        "items": result,
        "criteria": request.GET["criteria"].lower().strip()
    }

    return render(request, "trash/searchresult.html", context)


def openmap(request):  # open map page
    # get the coordinates list from opendata
    r = requests.get("http://opendata.lounaistieto.fi/aineistoja/Roskikset_geojson.geojson")
    if r.status_code != 404 and r.status_code != 403:
        data = r.json()
    else:
        # in case it is failed, use the local file
        my_dir = os.path.dirname(__file__)
        path = os.path.join(my_dir, 'static/trash/json/Roskikset_geojson.geojson')
        with open(path) as f:
            data = json.load(f)

    return render(request, "trash/maps.html", {"data": json.dumps(data)})


class AboutUs(View):
    def get(self, request):
        return render(request, "trash/aboutus.html")

    def post(self, request):
        pass


class LogIn(View):
    def get(self, request):
        return render(request, "trash/login.html")

    def post(self, request):
        data = request.POST

        user = auth.authenticate(email=data["email"], username=data["email"], password=data["password"])
        if user is not None and user.is_active:
            auth.login(request, user)
            messages.add_message(request, messages.SUCCESS, LOGGED_IN_MESSAGE, SUCCESS_CSS_TAGS)
            return HttpResponseRedirect(reverse("index"))
        else:
            messages.add_message(request, messages.ERROR, LOGGED_IN_NOT_SUCCESSFULLY_MESSAGE, ERROR_CSS_TAGS)
            return render(request, "trash/login.html")


def logout(request):
    auth.logout(request)
    messages.add_message(request, messages.SUCCESS, LOGGED_OUT_MESSAGE, SUCCESS_CSS_TAGS)
    return HttpResponseRedirect(reverse("index"))


class Register(View):
    def get(self, request):
        return render(request, "trash/register.html")

    def post(self, request):
        data = request.POST

        # check password and confirm_password match or not
        if data["password"] != data["confirm_password"]:
            messages.add_message(request, messages.ERROR, PASSWORD_CONFIRMATION_NOT_MATCH_MESSAGE, ERROR_CSS_TAGS)
            return render(request, "trash/register.html")

        # check unique username
        u = User.objects.filter(email=data["email"])
        if len(u) > 0:
            messages.add_message(request, messages.ERROR, USERNAME_EXISTED_MESSAGE, ERROR_CSS_TAGS)
            return render(request, "trash/register.html")

        new_user = User.objects.create_user(data["email"], data["email"], data["password"])
        new_user.save()

        auth.login(request, new_user)

        messages.add_message(request, messages.SUCCESS, REGISTER_SUCCESSFULLY_MESSAGE, SUCCESS_CSS_TAGS)
        return HttpResponseRedirect(reverse("index"))


@ensure_csrf_cookie
def rate(request):
    if request.method == "POST":
        try:
            item = TrashItem.objects.get(pk=request.POST["item_id"])
        except TrashItem.DoesNotExist:
            trash_bin = TrashBin.objects.get(name=request.POST["bin_name"].lower())
            items = TrashItem.objects.filter(bin=trash_bin)

            messages.add_message(request, messages.ERROR, COMMON_ERROR_MESSAGE, ERROR_CSS_TAGS)
            return render(request, "trash/binitems.html", {"bin": trash_bin, "items": items})
        else:
            try:
                item_rating = ItemRating.objects.get(item=item, user=request.user)
            except ItemRating.DoesNotExist:
                item_rating = ItemRating.objects.create(item=item, user=request.user)
                item_rating.rate = 1
                item.total_rating += 1
            else:
                if item_rating.rate == 1:
                    item_rating.rate = 0
                    item.total_rating += -1
                    item.voted = "no"
                elif item_rating.rate == 0:
                    item_rating.rate = 1
                    item.total_rating += 1
                    item.voted = "yes"

            item_rating.save()
            item.save()

        result = {
            "item_id": item.id,
            "total_rating": item.total_rating
        }

        return JsonResponse(result)
    else:
        return HttpResponseRedirect(reverse("index"))

trash/templates/trash/aboutus.html
{% extends "trash/base.html" %}
{% block title %}
    HMR - About Us
{% endblock %}

{% block content %}
    <div style="margin-top:80px; padding-bottom:100px;">
        <div class="container-fluid">
            <div class="row row-content">
                <div class="col-xs-12 col-sm-9 col-sm-offset-2 col-md-8 col-md-offset-2">
                    <h2>Who are we?</h2>
                    <p>We are a team of 5 people who work together on the project to help people in recycling.</p>
                    <h3>Project members:</h3>
                    <strong>Project manager:</strong> Anisa GJINI (anisa.gjini@abo.fi)<br>
                    <strong>Project owner:</strong> Candice PERSIL (candice.persil@abo.fi)<br>
                    <strong>UI design, Front-End development:</strong> Ekaterina PETUKHOVA (ekaterina.petukhova@abo.fi)<br>
                    <strong>Back-End development:</strong> Andi DOMI (andi.domi@abo.fi), Cuong TRAN (huy.tran@abo.fi)
                    <p>Visit us on Facebook: <a target="_blank" href="https://www.facebook.com/HelpMeRecycle/"> Help Me Recycle </a></p>
                </div>
            </div>
            <div class="row row-content">
                <div class="col-xs-12 col-sm-9 col-sm-offset-2 col-md-8 col-md-offset-2">
                    <h2>About HMR</h2>
                    <p>HelpMeRecycle is a web application that helps people to recycle. If you don't know where
                        to throw your trash our application lets you scan the product bar-code or search it by title
                        and then displays the right trash bin and its location
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

trash/templates/trash/additem.html
{% extends "trash/base.html" %}
{% block title %}
    HMR - Add Item
{% endblock %}

{% block content %}
    <div style="margin-top:80px; padding-bottom:100px;">
        <div class="container-fluid">
            <div class="row row-content">
                <div class="col-xs-12 col-sm-9 col-sm-offset-2 col-md-6 col-md-offset-3">
                    <form class="form-horizontal" role="form" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <fieldset>
                            <legend>Add a new item to the database</legend>

                            <div class="form-group">
                                <label for="id_name" class="col-sm-2 control-label">Title*</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" id="id_name" name="name" placeholder="Enter The Title"  autofocus required>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="id_description" class="col-sm-2 control-label">Description*</label>
                                <div class="col-sm-10">
                                    <textarea class="form-control" id="id_description" name="description" style="resize: vertical" rows="2" maxlength="128" required></textarea>
                                </div>
                            </div>

{#                            <div class="form-group">#}
{#                                <label for="id_material" class="col-sm-2 control-label">Trash material*</label>#}
{#                                <div class="col-sm-10">#}
{#                                    <select id="id_material" name="material" class="form-control" required>#}
{#                                        {% for m in materials %}#}
{#                                            <option value="{{ m.id }}">{{ m.name | capfirst }}</option>#}
{#                                        {% endfor %}#}
{#                                    </select>#}
{#                                </div>#}
{#                            </div>#}

                             <div class="form-group">
                                <label for="id_bin" class="col-sm-2 control-label">Trash bin*</label>
                                <div class="col-sm-10">
                                    <select id="id_bin" name="bin" class="form-control" required>
                                        {% for b in bins %}
                                            <option value="{{ b.id }}">{{ b.name | capfirst }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="id_sc_code" class="col-sm-2 control-label" id="sc">Scanner code</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" id="id_sc_code" name="sc_code" placeholder="Enter The Scanner Code" value="{{ scanner }}"  >
                                </div>
                            </div>

                            <!--<div class="form-group">
                                <label for="id_item_img" class="col-sm-2 control-label">Image</label>
                                <div class="col-sm-10">
                                    <input id="id_item_img" name="item_img" type="file" accept="image/*;capture=camera">
                                </div>
                            </div>-->

                            {# TODO: display the input file for user on pc and display camera for user on phone #}

                        </fieldset>
                        <div class="form-group">
                            <div class="col-xs-12 col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success btn-lg">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

trash/templates/trash/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head
         content must come *after* these tags -->
    <title>{% block title %}{% endblock %}</title>
        <!-- Bootstrap -->
    {% load static %}
    <script src="{% static 'trash/js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'trash/js/jquery.cookie.js' %}"></script>
    <link href="{% static 'trash/bower_components/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'trash/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'trash/css/bootstrap-social.css' %}" rel="stylesheet">
    <link href="{% static 'trash/css/mystyles.css' %}" rel="stylesheet">
</head>

<body>
    <header class="row-header">
        <nav class="navbar navbar-default navbar-fixed-top navbar-green" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand logo_style" href="{% url 'index' %}" style="color:#FFF;font-weight:100;">
                        <img src="{% static 'trash/images/logo.png' %}" style="height:30px;margin-top:-5px;">
                    </a>
                </div><!-- / collapsed navbar-->

                <!-- start un-collapsed navbar-->
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">

                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li><a class="nav_right_link" id="logout"  href="{% url 'logout' %}">
                                <span class="glyphicon glyphicon-log-out"></span> Logout</a>
                            </li>
                        {% else %}
                            <li><a class="nav_right_link" id="login"  href="{% url 'login' %}">
                                <span class="glyphicon glyphicon-log-in"></span> Login</a>
                            </li>
                        {% endif %}

                        <li><a class="nav_right_link" id="aboutus"  href="{% url 'aboutus' %}">
                            <span class="glyphicon glyphicon-info-sign"></span> About us</a>
                        </li>
                    </ul>
                </div><!-- / un-collapsed navbar-->

            </div> <!-- /container -->
        </nav>
    </header>

    {% block content %}
    {% endblock %}
    {# Footer part #}
    {# Contains 3 buttons #}
    <footer>
        <div class="row row-content">
            <div class="navbar-fixed-bottom">
                <div class="col-xs-4 col-md-4">
                    <a href="{% url 'additem' %}">  {# go to the add item page #}
                        <button type="button" class="btn btn-success btn-lg bottom-btn">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        </button>
                    </a>
                </div>
                <div class="col-xs-4 col-md-4">
                    <a href="{% url 'index' %}">  {# home page #}
                        <button type="button" class="btn btn-success btn-lg bottom-btn">
                            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                        </button>
                    </a>
                </div>
                <div class="col-xs-4 col-md-4">
                    <a href="{% url 'trashbins' %}">  {# trash bin page #}
                        <button type="button" class="btn btn-success btn-lg bottom-btn">
                            <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </footer>

    {% load static %}
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.3.15/proj4-src.js"></script>
    <script src="{% static 'trash/js/cake.js' %}"></script>
    <script src="{% static 'trash/js/cake_calculate.js' %}"></script>
</body>
</html>

trash/templates/trash/binitems.html
{% extends "trash/base.html" %}
{% block title %}
    HMR - Bin
{% endblock %}
{% load static %}
{% block content %}
    <div style="margin-top:110px; padding-bottom:100px;">
        <div class="container-fluid">
            <div class="row row-content">
                <div class="col-xs-12 col-sm-3 col-sm-offset-2 col-md-3 col-lg-2 col-lg-offset-2">
                    <a href="{% url 'show_binitems' bin.name %}"><!--<div class="round bin_center" id="Paper">
                        <div class="bin_title"><h3>Paper</h3></div>
                    </div>-->
                    <div class="trash_bin"><img src="{% static 'trash/images/' %}{{ bin.name }}1.png"><h3>{{ bin.name | capfirst }}</h3></div></a>
                </div>
                <div class="col-xs-8 col-sm-5 col-md-3 col-lg-4">
                    <p>
                        <strong>General color in Finland:</strong> {{ bin.color | capfirst }} <br>
                        <strong>Where bin generally found:</strong> {{ bin.common_location | capfirst }} <br>
                        <strong>State of items:</strong> {{ bin.state_of_items | capfirst }} <br>
                        <strong>Items included: </strong> {{ bin.description | capfirst }}<br>
                        <strong>Items not included: </strong> {{ bin.not_included | capfirst }} <br>
                    </p>
                </div>
                <div class="col-xs-4 col-sm-2 col-md-2 col-lg-2">
                    <a href="{% url 'openmap' %}">
                        <!--<button type="button" class="btn btn-success btn-lg">Bins map</button>-->
                        <div class="bins_map"><img src="{% static 'trash/images/map.png' %}" id="map_icon">
                        <h4>Bins map</h4></div>
                    </a>
                </div>
            </div>
            <div class="row row-content">
                {% if messages %}
                    <div class="row row-content">
                        <ul class="center messages col-xs-12 col-sm-9 col-sm-offset-2 col-md-8 col-md-offset-2">
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}

                <div class="col-xs-12 col-sm-10 col-sm-offset-2 col-md-8 col-md-offset-2">

                    {% for i in items %}

                        <div class="media">
                            <form class="itemMediaForm" id="form{{ i.id }}" role="form" method="POST">
                                {% csrf_token %}
                                <a class="media-left">
                                    <img class="media-object crop-img" src="{% static 'trash/images/' %}{{ i.bin.name }}.png" alt="{{ i.bin.name }}">
                                </a>
                                <div class="media-body">
                                    <div class="media-heading">
                                        <h3>
                                            {{ i.name | capfirst | truncatechars:18 }}
                                            <div style="float:right;">
                                                <span class="label {{ i.bin.name }}" style="margin-right:5px;">{{ i.bin.name | capfirst }}</span>
                                                <span class="rating">{{ i.total_rating }}</span>
                                                {% if user.is_authenticated %}
                                                    {% if i.voted == "yes" %}
                                                        <a class="glyphicon glyphicon-thumbs-up rateButton" href="javascript:$('#form{{ i.id }}').submit()"></a>
                                                    {% else %}
                                                        <a class="glyphicon glyphicon-thumbs-up rateButton voteThumb" href="javascript:$('#form{{ i.id }}').submit()"></a>
                                                    {% endif %}
                                                {% else %}
                                                    <a class="glyphicon glyphicon-thumbs-up rateButton voteThumb"></a>
                                                {% endif %}
                                                <input type="hidden" name="item_id" value="{{ i.id }}">
                                                <input type="hidden" name="bin_name" value="{{ i.bin.name }}">
                                            </div>
                                        </h3>
                                    </div>
                                    <p style="margin-top: 40px">{{ i.description | capfirst | truncatechars:150 }}</p>
                                </div>
                            </form>
                        </div>

                    {% empty %}
                        <span>No item available.</span>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}